# Generated by Django 3.1.2 on 2020-11-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Anime_id', models.IntegerField()),
                ('Name', models.CharField(max_length=200)),
                ('Genre', models.CharField(max_length=300)),
                ('Type', models.CharField(max_length=200)),
                ('Episode', models.IntegerField()),
                ('Rating', models.FloatField()),
                ('Members', models.IntegerField()),
            ],
            options={
                'verbose_name': 'AnimeModel',
                'verbose_name_plural': 'AnimeModels',
            },
        ),
        migrations.DeleteModel(
            name='ProductModel',
        ),
    ]
